### ISSUE TITLE
[UX] [mobile] [low-prio] comments section

### ISSUE THREAD

**Issue by TheAlan404** [kuylar/lighttube#10]
comments should be a popup like modern YouTube tbh, but idk how you would make something with css only

**Comment by kuylar** [comment]
Do you have a screenshot example?

**Comment by ashley0143** [comment]
like you can use the :target element in css, like how i do it on poketube:
![Screen Shot 2023-01-24 at 18 14 48](https://user-images.githubusercontent.com/65588168/214332539-617d2250-f4c1-4f18-bfd1-7ee2afcff27e.png)

if you want help, dm me on discord
