### ISSUE TITLE
[Bug] Loading circles after a video ends

### ISSUE THREAD

**Issue by NoxStellans** [kuylar/LightTube#104]
### Describe the bug

This is occurring on both lighttube.kuylar.dev and lighttube.plerx.de. For some reason, after a video finishes, a loading circle appears and continues to spin without going away. It's not a major issue, but I find this rather annoying. If there's anything that can be done to fix it, I'd be very grateful! I've attached an example of the issue below.

![Screenshot 2023-12-23 115033](https://github.com/kuylar/LightTube/assets/130122911/a20e8050-8c0e-4355-a6f2-0ac03fc1a266)

**Comment by kuylar** [comment]
known issue because i spent a total of 30 seconds to implement a loading spinner (no im not joking)

ive been trying to find the motivation to fix this and this is the one

a fix should be up in a week

**Comment by NoxStellans** [comment]
XD Fair enough, thanks for the response!
