### ISSUE TITLE
update README to not link to outdated gitlab repos

### ISSUE THREAD

**Issue by InFTord** [kuylar/lighttube#2]
yes

**Comment by InFTord** [comment]
**
![изображение](https://user-images.githubusercontent.com/60395110/205484079-2d321b28-adc3-48d1-9b01-546aae86726c.png)
**

**Comment by InFTord** [comment]
these links :yep:

**Comment by kuylar** [comment]
Links fixed, screenshots updated, will have to write the wikis soon 👍
