### ISSUE TITLE
[Bug] Trying to view shorts just throws an error/Doesn't Redirect to videos correctly.

### ISSUE THREAD

**Issue by CarlTheObeseCat** [kuylar/lighttube#26]
### Describe what happened

Clicking on a short redirects to a video with a blank id of {v}.

### Instance URL

https://tube.kuylar.dev/

### LightTube & InnerTube versions

v2023.3.6

### Resource path

Any Short video

### Language & region

En_UK

### Stack trace

Whoops!
This video isn't available any more

**Comment by kuylar** [comment]
Fixed, waiting on https://github.com/kuylar/InnerTube/pull/6 to merge & publish
