### ISSUE TITLE
[Feature Request] set "outline" CSS property to "none" for the search bar

### ISSUE THREAD

**Issue by Spelis123** [kuylar/lighttube#37]
### Description

the search bar looks weird because of the outline when focusing the element.

### Describe the solution you'd like

simply set the outline property to none

**Comment by dsezerpy** [comment]
Just to make it clear, you want the highlight of the selected search bar to go away, and the search bar to stay like this right?

![image](https://user-images.githubusercontent.com/29955189/236253417-77795a32-845d-4614-9f08-1da0aa912e63.png)

**Comment by Spelis123** [comment]
correct.

**Comment by dsezerpy** [comment]
waiting for @kuylar to merge pr now

**Comment by Spelis123** [comment]
sounds good
