### ISSUE TITLE
kuylar come back :(

### ISSUE THREAD

**Issue by InFTord** [kuylar/lighttube#5]
kuylar where are you :(
did discord got banned in turkey or what

**Comment by OoLunar** [comment]
+1

**Comment by Scordium** [comment]
+1

**Comment by Naamloos** [comment]
+1

**Comment by toasty1307** [comment]
+1

**Comment by Naamloos** [comment]
> kuylar where are you :( did discord got banned in turkey or what

Will set up matrix for y'all if it did

**Comment by CrabbyLT** [comment]
+1
