### ISSUE TITLE
[Feature Request] Let the default theme for instances be dark theme

### ISSUE THREAD

**Issue by Imzxhir** [kuylar/lighttube#50]
### Description

I would like a feature where dark theme is the default theme when the user loads the instance up for the first time. I know this option is decided by instance owners but, I feel like a system-bound dark mode could be cool and great if it was implemented

### Describe the solution you'd like

The solution I would like is the page to be dark mode when the user loads the page up for the first time, or I would like a feature where if the device theme is dark mode, then the website should be dark mode as well to suit the users theme choice.

### Describe alternatives you've considered

I have not considered any alternatives.

**Comment by Imzxhir** [comment]
Can this be closed as it seems to be implemented in this PR (https://github.com/kuylar/lighttube/pull/51) that was merged 13 hours ago?

**Comment by kuylar** [comment]
i thought GitHub would auto close this 💀
