### ISSUE TITLE
Sign in where I should sign up

### ISSUE THREAD

**Issue by OoLunar** [kuylar/lighttube#6]
https://tube.kuylar.dev/account/register
![image](https://user-images.githubusercontent.com/46751150/209272926-a40f3f31-8de7-4020-9913-f7424cd5ae21.png)

**Comment by InFTord** [comment]
sign in

sign in


there is no way that you could sign up

**Comment by kuylar** [comment]
![image](https://user-images.githubusercontent.com/52961639/210141252-51c2e6c7-519a-4614-8e14-88e148c0fc2b.png)

works in my machine
