### ISSUE TITLE
[Bug] Duplicate home tab in channel view

### ISSUE THREAD

**Issue by lo-kiss** [kuylar/lighttube#62]
### Describe the bug

The home tab gets duplicated in the channel view

Screenshot:
![image](https://github.com/kuylar/lighttube/assets/115636509/566d7c05-83dd-4efb-9cfe-144bc2837778)

I tested on other channels and it doesn't seem to happen on them. Only this one. Refreshed multiple times and tried in a new page, but it still happens.

**Comment by kuylar** [comment]
Related to kuylar/InnerTube#26
