### ISSUE TITLE
[Feature Request] Sponsorblock and DeArrow support

### ISSUE THREAD

**Issue by Terkyz** [kuylar/LightTube#68]
### Description

At this point I suppose you already know it, but [Sponsorblock](https://sponsor.ajay.app/) helps to skip different fragments of the video such as sponsors, filler content or music unrelated to the video. While [DeArrow](https://dearrow.ajay.app/) adds the ability to change the video thumbnail and title to something less "sensationalist".

### Describe the solution you'd like

That both DeArrow and Sponsorblock are integrated within LightTube.

**Comment by InFTord** [comment]
iirc there is some work on integrating that

**Comment by kuylar** [comment]
SponsorBlock is (in a very basic state) implemented with 5fd6f804e99cfbfb8b937dcaf66c253ba776ae92, and currently live on https://tube-nightly.kuylar.dev, will test it for some time then merge it to master.

DeArrow seems harder to implement though, I will have to look into that
