### ISSUE TITLE
[Feature Request] Ability to add as a search provider on browsers 

### ISSUE THREAD

**Issue by lo-kiss** [kuylar/LightTube#81]
### Description

On Firefox, you can add a custom search provider by right-clicking the search bar of the specific website (if it supports it) and clicking the 'Add as "X"' option. It would integrate well with my workflow and allow me to skip a few steps to get to the search.

How it should look:
![image](https://github.com/kuylar/LightTube/assets/115636509/fc86954a-f9a3-4731-a9b6-6be73374ac8e)

Also, thanks for your time! :)

### Describe the solution you'd like

I unfortunately don't know the details of implementing this, but this might be of interest:
https://en.wikipedia.org/wiki/OpenSearch

**Comment by dsezerpy** [comment]
If kuylar asignes this to me i'll give it a try, looks like a good idea to
add to LT to me.
